[package]
name = "oneflow_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oneflow_deps = { path = "../../../crates/oneflow_deps" }
